<?php

namespace Phactory;

use \Phactory;

/**
 * Represents a relationship between factories. A comment factory may require
 * an attribute called user, generated by an user factory.
 */
class HasOneRelationship
{
    /**
     * Factory name
     * @var string
     */
    private $name;

    /**
     * Variation or fixture name
     * @var string
     */
    private $type;

    /**
     * Attributes to override
     * @var array
     */
    private $override;

    /**
     * Constructor
     * @param string $name factory name
     * @param string $type variation or fixture name
     * @param array $override attributes to override
     */
    public function __construct($name, $type, $override)
    {
        $this->name = $name;
        $this->type = $type;
        $this->override = $override;
    }

    /**
     * Creates the relationship object
     * @param boolean $persisted
     * @return array|object
     */
    public function create($persisted = true)
    {
        return Phactory::createBlueprint($this->name, $this->type, $this->override, $persisted);
    }
}
